export const LANGUAGES = ['hy', 'en', 'ru', 'es', 'fr', 'de', 'it'];

export const LANGUAGE_NAMES = {
  hy: 'Հայերեն', en: 'English', ru: 'Русский', es: 'Español',
  fr: 'Français', de: 'Deutsch', it: 'Italiano'
};

const common = {
  invitation_url: 'Invitation URL', no_message: ''
};

const texts = {
  en: {
    welcome: '<b>Welcome to Amulet, {name}!</b>\n\nYour account is connected securely. New guest replies can now arrive here automatically.',
    welcome_back: '<b>Welcome back, {name}!</b>\n\nManage your invitations and guest replies from this menu.',
    not_connected: '<b>Your Amulet account is not connected.</b>\n\nOpen Profile on the website, press “Connect Telegram”, then press Start here.',
    expired: '<b>This connection link is invalid or has expired.</b>\n\nCreate a new link from your Amulet Profile and try again.',
    api_unavailable: '<b>Amulet could not complete the connection.</b>\n\nPlease try again shortly. Your link remains safe; if needed, create a new one from your Profile.',
    error: '<b>Something went wrong.</b>\n\nPlease try again. If the problem continues, contact Amulet support.',
    menu_title: '<b>Amulet assistant</b>\n\nChoose what you want to view or manage.',
    invitations: 'My invitations', language: 'Language', notifications_on: 'Notifications: ON', notifications_off: 'Notifications: OFF', help: 'Help', disconnect: 'Disconnect Telegram', back: 'Back',
    open_invitation: 'Open invitation', guest_replies: 'Guest replies',
    no_invitations: '<b>No purchased invitations yet.</b>\n\nThey will appear here after your purchase is completed.',
    invitations_title: '<b>Your invitations</b>\n\nSelect an invitation to see its details.',
    invitation_details: '<b>{title}</b>\nTemplate: {template}\nDate: {date}\nTime: {time}\nLocation: {location}\n\nReplies: <b>{replies}</b> · Guests: <b>{guests}</b>',
    no_replies: '<b>No guest replies yet.</b>\n\nNew submissions will appear here and arrive as notifications when enabled.',
    replies_title: '<b>Guest replies — {title}</b>\nPage {page}/{pages}\n\n{items}',
    reply_item: '{icon} <b>{name}</b> · {count}\n{status} · {phone}{message}', previous: 'Previous', next: 'Next',
    choose_language: '<b>Choose the bot language</b>', language_saved: 'Language updated.',
    notifications_enabled: 'Automatic guest reply notifications are now enabled.', notifications_disabled: 'Automatic guest reply notifications are now paused.',
    help_text: '<b>How Amulet Bot works</b>\n\n• New guest replies arrive automatically.\n• “My invitations” shows purchased invitations.\n• Open one to view its replies.\n• Change language or pause notifications anytime.',
    disconnect_confirm: '<b>Disconnect Telegram?</b>\n\nAutomatic guest reply notifications will stop.', disconnect_yes: 'Yes, disconnect', cancel: 'Cancel',
    disconnected: '<b>Telegram was disconnected.</b>\n\nYou can connect it again from your Amulet Profile.',
    attending: 'Attending', declined: 'Not attending', unsure: 'Not sure', guests: '{count} guest(s)'
  },
  hy: {
    welcome: '<b>Բարի գալուստ Amulet, {name}՛</b>\n\nՁեր հաշիվն անվտանգ կապվեց։ Հյուրերի նոր պատասխաններն այսուհետ կարող են ավտոմատ հասնել այստեղ։',
    welcome_back: '<b>Բարի վերադարձ, {name}՛</b>\n\nԱյս բաժնից կառավարեք հրավիրատոմսերն ու հյուրերի պատասխանները։',
    not_connected: '<b>Ձեր Amulet հաշիվը դեռ կապակցված չէ։</b>\n\nԿայքի Profile բաժնում սեղմեք «Միացնել Telegram-ը», ապա այստեղ՝ Start։',
    expired: '<b>Կապման հղումը սխալ է կամ ժամկետանց։</b>\n\nProfile-ից ստեղծեք նոր հղում և կրկին փորձեք։',
    api_unavailable: '<b>Amulet-ին չհաջողվեց ավարտել կապակցումը։</b>\n\nՓորձեք կրկին մի փոքր անց։ Հղումն անվտանգ է, իսկ անհրաժեշտության դեպքում Profile-ից ստեղծեք նորը։',
    error: '<b>Ինչ-որ բան սխալ ընթացավ։</b>\n\nԽնդրում ենք կրկին փորձել։ Եթե խնդիրը շարունակվի, կապվեք Amulet-ի աջակցության հետ։',
    menu_title: '<b>Amulet օգնական</b>\n\nԸնտրեք՝ ինչ եք ցանկանում դիտել կամ կարգավորել։',
    invitations: 'Իմ հրավիրատոմսերը', language: 'Լեզու', notifications_on: 'Ծանուցումներ՝ ՄԻԱՑՎԱԾ', notifications_off: 'Ծանուցումներ՝ ԱՆՋԱՏՎԱԾ', help: 'Օգնություն', disconnect: 'Անջատել Telegram-ը', back: 'Հետ',
    open_invitation: 'Բացել հրավիրատոմսը', guest_replies: 'Հյուրերի պատասխանները',
    no_invitations: '<b>Գնված հրավիրատոմսեր դեռ չկան։</b>\n\nԳնումն ավարտելուց հետո դրանք կհայտնվեն այստեղ։', invitations_title: '<b>Ձեր հրավիրատոմսերը</b>\n\nԸնտրեք հրավիրատոմսը՝ մանրամասները տեսնելու համար։',
    invitation_details: '<b>{title}</b>\nՇաբլոն՝ {template}\nԱմսաթիվ՝ {date}\nԺամ՝ {time}\nՎայր՝ {location}\n\nՊատասխաններ՝ <b>{replies}</b> · Հյուրեր՝ <b>{guests}</b>', invitation_url: 'Հրավիրատոմսի հասցե',
    no_replies: '<b>Հյուրերի պատասխաններ դեռ չկան։</b>\n\nՆոր պատասխանները կհայտնվեն այստեղ և, եթե միացված է, կգան որպես ծանուցում։',
    replies_title: '<b>Հյուրերի պատասխաններ — {title}</b>\nԷջ {page}/{pages}\n\n{items}', reply_item: '{icon} <b>{name}</b> · {count}\n{status} · {phone}{message}', previous: 'Նախորդ', next: 'Հաջորդ',
    choose_language: '<b>Ընտրեք բոտի լեզուն</b>', language_saved: 'Լեզուն փոխված է։', notifications_enabled: 'Հյուրերի նոր պատասխանների ավտոմատ ծանուցումները միացված են։', notifications_disabled: 'Հյուրերի պատասխանների ավտոմատ ծանուցումները դադարեցված են։',
    help_text: '<b>Ինչպես է աշխատում Amulet Bot-ը</b>\n\n• Հյուրերի նոր պատասխաններն ավտոմատ կգան այստեղ։\n• «Իմ հրավիրատոմսերը» բաժինը ցույց է տալիս գնումները։\n• Բացեք հրավիրատոմսը՝ պատասխանները տեսնելու համար։\n• Ցանկացած պահի փոխեք լեզուն կամ դադարեցրեք ծանուցումները։',
    disconnect_confirm: '<b>Անջատե՞լ Telegram-ը։</b>\n\nՀյուրերի ավտոմատ ծանուցումները կդադարեն։', disconnect_yes: 'Այո, անջատել', cancel: 'Չեղարկել', disconnected: '<b>Telegram-ն անջատված է։</b>\n\nԿարող եք կրկին կապել այն Amulet Profile-ից։',
    attending: 'Գալու է', declined: 'Չի գալու', unsure: 'Դեռ վստահ չէ', guests: '{count} հյուր'
  },
  ru: {
    welcome: '<b>Добро пожаловать в Amulet, {name}!</b>\n\nВаш аккаунт безопасно подключён. Новые ответы гостей теперь могут приходить сюда автоматически.', welcome_back: '<b>С возвращением, {name}!</b>\n\nУправляйте приглашениями и ответами гостей в этом меню.', not_connected: '<b>Ваш аккаунт Amulet не подключён.</b>\n\nВ профиле на сайте нажмите «Подключить Telegram», затем Start здесь.', expired: '<b>Ссылка подключения недействительна или устарела.</b>\n\nСоздайте новую ссылку в профиле.', api_unavailable: '<b>Не удалось завершить подключение к Amulet.</b>\n\nПовторите попытку немного позже.', error: '<b>Что-то пошло не так.</b>\n\nПовторите попытку или обратитесь в поддержку Amulet.', menu_title: '<b>Помощник Amulet</b>\n\nВыберите нужный раздел.', invitations: 'Мои приглашения', language: 'Язык', notifications_on: 'Уведомления: ВКЛ', notifications_off: 'Уведомления: ВЫКЛ', help: 'Помощь', disconnect: 'Отключить Telegram', back: 'Назад', open_invitation: 'Открыть приглашение', guest_replies: 'Ответы гостей', no_invitations: '<b>Купленных приглашений пока нет.</b>', invitations_title: '<b>Ваши приглашения</b>\n\nВыберите приглашение.', invitation_details: '<b>{title}</b>\nШаблон: {template}\nДата: {date}\nВремя: {time}\nМесто: {location}\n\nОтветов: <b>{replies}</b> · Гостей: <b>{guests}</b>', no_replies: '<b>Ответов гостей пока нет.</b>', replies_title: '<b>Ответы гостей — {title}</b>\nСтраница {page}/{pages}\n\n{items}', reply_item: '{icon} <b>{name}</b> · {count}\n{status} · {phone}{message}', previous: 'Назад', next: 'Далее', choose_language: '<b>Выберите язык бота</b>', language_saved: 'Язык обновлён.', notifications_enabled: 'Автоматические уведомления включены.', notifications_disabled: 'Автоматические уведомления приостановлены.', help_text: '<b>Как работает Amulet Bot</b>\n\n• Ответы гостей приходят автоматически.\n• Здесь доступны ваши приглашения и ответы.\n• Язык и уведомления можно изменить в любое время.', disconnect_confirm: '<b>Отключить Telegram?</b>', disconnect_yes: 'Да, отключить', cancel: 'Отмена', disconnected: '<b>Telegram отключён.</b>', attending: 'Будет', declined: 'Не будет', unsure: 'Не уверен(а)', guests: '{count} гост.'
  },
  es: { welcome: '<b>¡Bienvenido a Amulet, {name}!</b>\n\nTu cuenta está conectada de forma segura.', welcome_back: '<b>¡Bienvenido de nuevo, {name}!</b>', not_connected: '<b>Tu cuenta de Amulet no está conectada.</b>\n\nPulsa «Conectar Telegram» en tu perfil y luego Start aquí.', expired: '<b>El enlace no es válido o ha caducado.</b>', api_unavailable: '<b>No se pudo completar la conexión con Amulet.</b>\n\nInténtalo de nuevo en breve.', error: '<b>Algo salió mal.</b>\n\nInténtalo de nuevo.', menu_title: '<b>Asistente Amulet</b>\n\nElige una opción.', invitations: 'Mis invitaciones', language: 'Idioma', notifications_on: 'Notificaciones: ACTIVAS', notifications_off: 'Notificaciones: PAUSADAS', help: 'Ayuda', disconnect: 'Desconectar Telegram', back: 'Atrás', open_invitation: 'Abrir invitación', guest_replies: 'Respuestas', no_invitations: '<b>Aún no hay invitaciones compradas.</b>', invitations_title: '<b>Tus invitaciones</b>', invitation_details: '<b>{title}</b>\nPlantilla: {template}\nFecha: {date}\nHora: {time}\nLugar: {location}\n\nRespuestas: <b>{replies}</b> · Invitados: <b>{guests}</b>', no_replies: '<b>Aún no hay respuestas.</b>', replies_title: '<b>Respuestas — {title}</b>\nPágina {page}/{pages}\n\n{items}', reply_item: '{icon} <b>{name}</b> · {count}\n{status} · {phone}{message}', previous: 'Anterior', next: 'Siguiente', choose_language: '<b>Elige el idioma del bot</b>', language_saved: 'Idioma actualizado.', notifications_enabled: 'Las notificaciones automáticas están activadas.', notifications_disabled: 'Las notificaciones automáticas están pausadas.', help_text: '<b>Cómo funciona Amulet Bot</b>\n\n• Recibe respuestas automáticamente.\n• Consulta tus invitaciones y respuestas.\n• Cambia idioma o avisos cuando quieras.', disconnect_confirm: '<b>¿Desconectar Telegram?</b>', disconnect_yes: 'Sí, desconectar', cancel: 'Cancelar', disconnected: '<b>Telegram está desconectado.</b>', attending: 'Asistirá', declined: 'No asistirá', unsure: 'No está seguro', guests: '{count} invitado(s)' },
  fr: { welcome: '<b>Bienvenue sur Amulet, {name} !</b>\n\nVotre compte est connecté en toute sécurité.', welcome_back: '<b>Bon retour, {name} !</b>', not_connected: '<b>Votre compte Amulet n’est pas connecté.</b>\n\nAppuyez sur « Connecter Telegram » dans votre profil, puis sur Start ici.', expired: '<b>Ce lien est invalide ou expiré.</b>', api_unavailable: '<b>Impossible de terminer la connexion à Amulet.</b>\n\nVeuillez réessayer bientôt.', error: '<b>Une erreur est survenue.</b>\n\nVeuillez réessayer.', menu_title: '<b>Assistant Amulet</b>\n\nChoisissez une option.', invitations: 'Mes invitations', language: 'Langue', notifications_on: 'Notifications : ACTIVÉES', notifications_off: 'Notifications : PAUSÉES', help: 'Aide', disconnect: 'Déconnecter Telegram', back: 'Retour', open_invitation: 'Ouvrir l’invitation', guest_replies: 'Réponses', no_invitations: '<b>Aucune invitation achetée.</b>', invitations_title: '<b>Vos invitations</b>', invitation_details: '<b>{title}</b>\nModèle : {template}\nDate : {date}\nHeure : {time}\nLieu : {location}\n\nRéponses : <b>{replies}</b> · Invités : <b>{guests}</b>', no_replies: '<b>Aucune réponse pour le moment.</b>', replies_title: '<b>Réponses — {title}</b>\nPage {page}/{pages}\n\n{items}', reply_item: '{icon} <b>{name}</b> · {count}\n{status} · {phone}{message}', previous: 'Précédent', next: 'Suivant', choose_language: '<b>Choisissez la langue du bot</b>', language_saved: 'Langue mise à jour.', notifications_enabled: 'Les notifications automatiques sont activées.', notifications_disabled: 'Les notifications automatiques sont en pause.', help_text: '<b>Fonctionnement d’Amulet Bot</b>\n\n• Recevez les réponses automatiquement.\n• Consultez vos invitations et réponses.\n• Modifiez la langue ou les notifications à tout moment.', disconnect_confirm: '<b>Déconnecter Telegram ?</b>', disconnect_yes: 'Oui, déconnecter', cancel: 'Annuler', disconnected: '<b>Telegram est déconnecté.</b>', attending: 'Présent', declined: 'Absent', unsure: 'Incertain', guests: '{count} invité(s)' },
  de: { welcome: '<b>Willkommen bei Amulet, {name}!</b>\n\nIhr Konto ist sicher verbunden.', welcome_back: '<b>Willkommen zurück, {name}!</b>', not_connected: '<b>Ihr Amulet-Konto ist nicht verbunden.</b>\n\nKlicken Sie im Profil auf „Telegram verbinden“ und danach hier auf Start.', expired: '<b>Der Link ist ungültig oder abgelaufen.</b>', api_unavailable: '<b>Die Verbindung zu Amulet konnte nicht abgeschlossen werden.</b>\n\nBitte versuchen Sie es gleich noch einmal.', error: '<b>Etwas ist schiefgelaufen.</b>\n\nBitte versuchen Sie es erneut.', menu_title: '<b>Amulet-Assistent</b>\n\nWählen Sie eine Option.', invitations: 'Meine Einladungen', language: 'Sprache', notifications_on: 'Benachrichtigungen: AN', notifications_off: 'Benachrichtigungen: PAUSIERT', help: 'Hilfe', disconnect: 'Telegram trennen', back: 'Zurück', open_invitation: 'Einladung öffnen', guest_replies: 'Gästeantworten', no_invitations: '<b>Noch keine gekauften Einladungen.</b>', invitations_title: '<b>Ihre Einladungen</b>', invitation_details: '<b>{title}</b>\nVorlage: {template}\nDatum: {date}\nUhrzeit: {time}\nOrt: {location}\n\nAntworten: <b>{replies}</b> · Gäste: <b>{guests}</b>', no_replies: '<b>Noch keine Gästeantworten.</b>', replies_title: '<b>Gästeantworten — {title}</b>\nSeite {page}/{pages}\n\n{items}', reply_item: '{icon} <b>{name}</b> · {count}\n{status} · {phone}{message}', previous: 'Zurück', next: 'Weiter', choose_language: '<b>Bot-Sprache auswählen</b>', language_saved: 'Sprache aktualisiert.', notifications_enabled: 'Automatische Benachrichtigungen sind aktiviert.', notifications_disabled: 'Automatische Benachrichtigungen sind pausiert.', help_text: '<b>So funktioniert Amulet Bot</b>\n\n• Antworten kommen automatisch an.\n• Hier sehen Sie Einladungen und Antworten.\n• Sprache und Meldungen lassen sich jederzeit ändern.', disconnect_confirm: '<b>Telegram trennen?</b>', disconnect_yes: 'Ja, trennen', cancel: 'Abbrechen', disconnected: '<b>Telegram wurde getrennt.</b>', attending: 'Nimmt teil', declined: 'Nimmt nicht teil', unsure: 'Unsicher', guests: '{count} Gast/Gäste' },
  it: { welcome: '<b>Benvenuto su Amulet, {name}!</b>\n\nIl tuo account è collegato in modo sicuro.', welcome_back: '<b>Bentornato, {name}!</b>', not_connected: '<b>Il tuo account Amulet non è collegato.</b>\n\nNel profilo premi «Collega Telegram», poi premi Start qui.', expired: '<b>Il link non è valido o è scaduto.</b>', api_unavailable: '<b>Impossibile completare il collegamento ad Amulet.</b>\n\nRiprova tra poco.', error: '<b>Qualcosa è andato storto.</b>\n\nRiprova.', menu_title: '<b>Assistente Amulet</b>\n\nScegli un’opzione.', invitations: 'I miei inviti', language: 'Lingua', notifications_on: 'Notifiche: ATTIVE', notifications_off: 'Notifiche: IN PAUSA', help: 'Aiuto', disconnect: 'Scollega Telegram', back: 'Indietro', open_invitation: 'Apri invito', guest_replies: 'Risposte', no_invitations: '<b>Nessun invito acquistato.</b>', invitations_title: '<b>I tuoi inviti</b>', invitation_details: '<b>{title}</b>\nModello: {template}\nData: {date}\nOra: {time}\nLuogo: {location}\n\nRisposte: <b>{replies}</b> · Ospiti: <b>{guests}</b>', no_replies: '<b>Ancora nessuna risposta.</b>', replies_title: '<b>Risposte — {title}</b>\nPagina {page}/{pages}\n\n{items}', reply_item: '{icon} <b>{name}</b> · {count}\n{status} · {phone}{message}', previous: 'Precedente', next: 'Successivo', choose_language: '<b>Scegli la lingua del bot</b>', language_saved: 'Lingua aggiornata.', notifications_enabled: 'Le notifiche automatiche sono attive.', notifications_disabled: 'Le notifiche automatiche sono in pausa.', help_text: '<b>Come funziona Amulet Bot</b>\n\n• Ricevi automaticamente le risposte.\n• Visualizza inviti e risposte.\n• Cambia lingua o avvisi in qualsiasi momento.', disconnect_confirm: '<b>Scollegare Telegram?</b>', disconnect_yes: 'Sì, scollega', cancel: 'Annulla', disconnected: '<b>Telegram è stato scollegato.</b>', attending: 'Parteciperà', declined: 'Non parteciperà', unsure: 'Non è sicuro', guests: '{count} ospite/i' }
};

export const normalizeLanguage = (language, fallback = 'en') => {
  const candidate = String(language || '').split('-')[0].toLowerCase();
  return LANGUAGES.includes(candidate) ? candidate : fallback;
};

export const tr = (language, key, values = {}) => {
  const template = texts[normalizeLanguage(language)]?.[key] ?? texts.en[key] ?? common[key] ?? key;
  return Object.entries(values).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template
  );
};

