import React from 'react';
import { Quote, Sparkles } from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext.jsx';

const hyTexts = [
  'Շատ գեղեցիկ և նուրբ հրավիրատոմս ստացանք։ Ամեն ինչ ճաշակով էր արված։',
  'Amulet-ի միջոցով մեր հարսանիքի հրավիրատոմսը դարձավ ավելի յուրահատուկ ու ժամանակակից։',
  'Շատ հարմար տարբերակ է․ ուղարկում ես հղումը, և հյուրերը միանգամից տեսնում են ամբողջ ինֆորմացիան։',
  'Դիզայնը շատ պրեմիում էր, իսկ օգտագործումը՝ շատ պարզ։',
  'Շնորհակալ ենք գեղեցիկ աշխատանքի համար։ Մեր հյուրերը շատ հավանեցին հրավիրատոմսը։',
  'Ամեն ինչ պատրաստվեց արագ, գեղեցիկ և շատ կոկիկ։',
  'Շատ ուրախ ենք, որ ընտրեցինք Amulet-ը։ Հրավիրատոմսը ստացվեց հենց այնպիսին, ինչպիսին պատկերացնում էինք։',
  'Նուրբ գույներ, գեղեցիկ դիզայն և շատ հարմար լուծում։',
  'Մեր նշանադրության հրավիրատոմսը շատ էլեգանտ էր։ Շնորհակալություն։',
  'Հրաշալի տարբերակ է նրանց համար, ովքեր ուզում են ժամանակակից և գեղեցիկ հրավիրատոմս։',
  'Ամեն մանրուք մտածված էր։ Շատ հաճելի արդյունք ստացվեց։',
  'Հյուրերը միանգամից կարողացան տեսնել վայրը, ժամը և ամբողջ մանրամասները։',
  'Շատ որակյալ և գեղեցիկ աշխատանք։ Անպայման խորհուրդ կտամ։',
  'Amulet-ը մեր միջոցառմանը հատուկ շունչ տվեց։',
  'Շատ սիրուն, նուրբ և հիշվող հրավիրատոմս էր։',
  'Արագ պատրաստեցին, բոլոր փոփոխություններն էլ սիրով արեցին։',
  'Դիզայնը շատ բարձր մակարդակի էր։ Շատ գոհ ենք։',
  'Մեր մկրտության հրավիրատոմսը ստացվեց շատ քնքուշ ու գեղեցիկ։',
  'Շատ հարմար է, որ թղթային հրավիրատոմսի կարիք չկա։',
  'Հղումը ուղարկեցինք բոլորին, և ամեն ինչ շատ հեշտ կազմակերպվեց։',
  'Գեղեցիկ, մաքուր և ժամանակակից լուծում։',
  'Ամեն ինչ շատ պրոֆեսիոնալ էր՝ սկսած դիզայնից մինչև վերջնական տեսք։',
  'Շատ շնորհակալ ենք այս գեղեցիկ հիշողության համար։',
  'Հրավիրատոմսը շատ ճաշակով էր և համապատասխանում էր մեր միջոցառման ոճին։',
  'Մեր ծննդյան միջոցառման հրավիրատոմսը շատ ուրախ և գեղեցիկ ստացվեց։',
  'Amulet-ը իսկապես առանձնահատուկ է դարձնում միջոցառումը։',
  'Շատ հեշտ էր օգտագործել, իսկ տեսքը՝ շատ գեղեցիկ։',
  'Մեր հյուրերից շատերը հարցրեցին՝ որտեղից ենք պատվիրել։',
  'Շատ գոհ ենք արդյունքից։ Ամեն ինչ գեղեցիկ և պարզ էր։',
  'Հրավիրատոմսը շատ տպավորիչ էր, հատկապես հեռախոսով բացելիս։',
  'Շատ նուրբ աշխատանք էր։ Ամեն դետալ իր տեղում էր։',
  'Amulet-ը հիանալի ընտրություն է ժամանակակից հրավիրատոմսի համար։',
  'Շատ գեղեցիկ էր, և ամենակարևորը՝ շատ հարմար։',
  'Մեր հարսանիքի հրավիրատոմսը դարձավ նաև գեղեցիկ հիշողություն։',
  'Շնորհակալություն արագ և որակյալ աշխատանքի համար։',
  'Դիզայնը շատ մաքուր էր, առանց ավելորդությունների։',
  'Ամեն ինչ պարզ, հասկանալի և գեղեցիկ էր ներկայացված։',
  'Շատ սիրեցինք վերջնական արդյունքը։ Հենց մեր ոճով էր։',
  'Amulet-ի հրավիրատոմսը մեր միջոցառմանը էլեգանտ սկիզբ տվեց։',
  'Շատ հարմար էր հյուրերի համար, հատկապես քարտեզի և մանրամասների բաժինը։',
  'Գեղեցիկ լուծում է ցանկացած միջոցառման համար։',
  'Մեր կորպորատիվ միջոցառման հրավիրատոմսը շատ պրոֆեսիոնալ տեսք ուներ։',
  'Շատ հաճելի էր աշխատել ձեզ հետ։ Ամեն ինչ արագ ու ճիշտ կազմակերպվեց։',
  'Հրավիրատոմսը ստացվեց շատ գեղեցիկ, ժամանակակից և հիշվող։',
  'Amulet-ը միանշանակ խորհուրդ կտամ ընկերներիս։',
  'Շատ լավ տարբերակ է, եթե ուզում եք տարբերվել սովորական հրավիրատոմսերից։',
  'Ամեն ինչ արված էր մեծ ճաշակով և ուշադրությամբ։',
  'Մեր հյուրերը շատ հեշտ գտան ամբողջ ինֆորմացիան մեկ տեղում։',
  'Շատ շնորհակալ ենք գեղեցիկ ու պրեմիում աշխատանքի համար։',
  'Amulet-ի շնորհիվ մեր հրավիրատոմսը դարձավ ոչ միայն տեղեկացնող, այլ նաև էմոցիոնալ ու գեղեցիկ փորձառություն։'
];

const localizedTexts = {
  hy: hyTexts,
  en: [
    'We received a very beautiful and delicate invitation. Everything was done with taste.',
    'With Amulet, our wedding invitation became more unique and modern.',
    'It is very convenient: you send the link and guests instantly see all the information.',
    'The design felt very premium, and using it was very simple.',
    'Thank you for the beautiful work. Our guests loved the invitation.',
    'Everything was prepared quickly, beautifully, and very neatly.',
    'We are very happy we chose Amulet. The invitation turned out exactly as we imagined.',
    'Soft colors, beautiful design, and a very convenient solution.',
    'Our engagement invitation was very elegant. Thank you.',
    'A wonderful option for people who want a modern and beautiful invitation.',
    'Every detail was thought through. The result was very pleasant.',
    'Guests immediately saw the place, time, and all the details.',
    'Very high-quality and beautiful work. I will definitely recommend it.',
    'Amulet gave our event a special feeling.',
    'It was a very lovely, delicate, and memorable invitation.',
    'They prepared it quickly and made every change with care.',
    'The design was at a very high level. We are very satisfied.',
    'Our baptism invitation turned out very tender and beautiful.',
    'It is very convenient that there is no need for paper invitations.',
    'We sent the link to everyone and everything was organized very easily.',
    'A beautiful, clean, and modern solution.',
    'Everything was very professional, from design to final look.',
    'Thank you so much for this beautiful memory.',
    'The invitation was tasteful and matched the style of our event.',
    'Our birthday invitation turned out very cheerful and beautiful.',
    'Amulet truly makes an event feel special.',
    'It was very easy to use, and the look was beautiful.',
    'Many of our guests asked where we ordered it from.',
    'We are very happy with the result. Everything was beautiful and clear.',
    'The invitation was impressive, especially when opened on a phone.',
    'It was very delicate work. Every detail was in its place.',
    'Amulet is an excellent choice for a modern invitation.',
    'It was beautiful, and most importantly, very convenient.',
    'Our wedding invitation also became a beautiful memory.',
    'Thank you for fast and high-quality work.',
    'The design was very clean, without anything unnecessary.',
    'Everything was presented clearly, simply, and beautifully.',
    'We loved the final result. It was exactly our style.',
    'The Amulet invitation gave our event an elegant beginning.',
    'It was very convenient for guests, especially the map and details section.',
    'A beautiful solution for any event.',
    'Our corporate event invitation looked very professional.',
    'It was very pleasant to work with you. Everything was organized quickly and correctly.',
    'The invitation turned out beautiful, modern, and memorable.',
    'I would definitely recommend Amulet to my friends.',
    'A great option if you want to stand out from ordinary invitations.',
    'Everything was done with great taste and attention.',
    'Our guests easily found all the information in one place.',
    'Thank you for the beautiful and premium work.',
    'Thanks to Amulet, our invitation became not only informative but also an emotional and beautiful experience.'
  ],
  fr: [
    'Nous avons reçu une invitation très belle et délicate. Tout était fait avec goût.',
    'Avec Amulet, notre invitation de mariage est devenue plus unique et moderne.',
    'C’est très pratique : on envoie le lien et les invités voient tout de suite toutes les informations.',
    'Le design était très premium et l’utilisation très simple.',
    'Merci pour ce beau travail. Nos invités ont beaucoup aimé l’invitation.',
    'Tout a été préparé rapidement, joliment et avec beaucoup de soin.',
    'Nous sommes très heureux d’avoir choisi Amulet. L’invitation était exactement comme nous l’imaginions.',
    'Des couleurs douces, un beau design et une solution très pratique.',
    'Notre invitation de fiançailles était très élégante. Merci.',
    'Une excellente option pour ceux qui veulent une invitation moderne et belle.',
    'Chaque détail était pensé. Le résultat a été très agréable.',
    'Les invités ont vu immédiatement le lieu, l’heure et tous les détails.',
    'Un travail très qualitatif et très beau. Je recommanderai sans hésiter.',
    'Amulet a donné une touche spéciale à notre événement.',
    'C’était une invitation très jolie, délicate et mémorable.',
    'Ils l’ont préparée rapidement et ont fait chaque modification avec attention.',
    'Le design était d’un très haut niveau. Nous sommes très satisfaits.',
    'Notre invitation de baptême était très tendre et belle.',
    'C’est très pratique de ne plus avoir besoin d’invitations papier.',
    'Nous avons envoyé le lien à tout le monde et tout s’est organisé très facilement.',
    'Une solution belle, propre et moderne.',
    'Tout était très professionnel, du design au rendu final.',
    'Merci beaucoup pour ce beau souvenir.',
    'L’invitation était de très bon goût et correspondait au style de notre événement.',
    'Notre invitation d’anniversaire était très joyeuse et belle.',
    'Amulet rend vraiment l’événement plus spécial.',
    'C’était très facile à utiliser et le rendu était magnifique.',
    'Beaucoup de nos invités ont demandé où nous l’avions commandée.',
    'Nous sommes très satisfaits du résultat. Tout était beau et clair.',
    'L’invitation était impressionnante, surtout ouverte sur téléphone.',
    'Un travail très délicat. Chaque détail était à sa place.',
    'Amulet est un excellent choix pour une invitation moderne.',
    'C’était beau et surtout très pratique.',
    'Notre invitation de mariage est aussi devenue un beau souvenir.',
    'Merci pour le travail rapide et de qualité.',
    'Le design était très propre, sans éléments inutiles.',
    'Tout était présenté simplement, clairement et joliment.',
    'Nous avons adoré le résultat final. C’était exactement notre style.',
    'L’invitation Amulet a donné un début élégant à notre événement.',
    'C’était très pratique pour les invités, surtout la carte et les détails.',
    'Une belle solution pour tout type d’événement.',
    'Notre invitation d’événement corporate avait un rendu très professionnel.',
    'C’était très agréable de travailler avec vous. Tout a été organisé vite et correctement.',
    'L’invitation était belle, moderne et mémorable.',
    'Je recommanderai clairement Amulet à mes amis.',
    'Une très bonne option pour se démarquer des invitations classiques.',
    'Tout a été fait avec beaucoup de goût et d’attention.',
    'Nos invités ont trouvé facilement toutes les informations au même endroit.',
    'Merci pour ce travail beau et premium.',
    'Grâce à Amulet, notre invitation est devenue non seulement informative, mais aussi une belle expérience émotionnelle.'
  ],
  es: [
    'Recibimos una invitación muy bonita y delicada. Todo estaba hecho con mucho gusto.',
    'Con Amulet, nuestra invitación de boda se volvió más única y moderna.',
    'Es muy cómodo: envías el enlace y los invitados ven toda la información al instante.',
    'El diseño se veía muy premium y el uso fue muy sencillo.',
    'Gracias por el hermoso trabajo. A nuestros invitados les encantó la invitación.',
    'Todo se preparó rápido, bonito y muy prolijo.',
    'Estamos muy felices de haber elegido Amulet. La invitación quedó exactamente como la imaginábamos.',
    'Colores suaves, diseño bonito y una solución muy práctica.',
    'Nuestra invitación de compromiso fue muy elegante. Gracias.',
    'Una opción maravillosa para quienes quieren una invitación moderna y bonita.',
    'Cada detalle estaba pensado. El resultado fue muy agradable.',
    'Los invitados pudieron ver enseguida el lugar, la hora y todos los detalles.',
    'Trabajo muy bonito y de mucha calidad. Sin duda lo recomendaré.',
    'Amulet le dio un toque especial a nuestro evento.',
    'Fue una invitación muy linda, delicada y memorable.',
    'La prepararon rápido e hicieron todos los cambios con mucho cariño.',
    'El diseño estaba a un nivel muy alto. Estamos muy satisfechos.',
    'Nuestra invitación de bautizo quedó muy tierna y bonita.',
    'Es muy cómodo no necesitar invitaciones en papel.',
    'Enviamos el enlace a todos y todo se organizó muy fácilmente.',
    'Una solución bonita, limpia y moderna.',
    'Todo fue muy profesional, desde el diseño hasta el resultado final.',
    'Muchas gracias por este hermoso recuerdo.',
    'La invitación tenía mucho gusto y encajaba con el estilo de nuestro evento.',
    'Nuestra invitación de cumpleaños quedó muy alegre y bonita.',
    'Amulet realmente hace que el evento se sienta especial.',
    'Fue muy fácil de usar y el aspecto era muy bonito.',
    'Muchos de nuestros invitados preguntaron dónde la habíamos pedido.',
    'Estamos muy contentos con el resultado. Todo fue bonito y claro.',
    'La invitación fue impactante, especialmente al abrirla en el teléfono.',
    'Un trabajo muy delicado. Cada detalle estaba en su lugar.',
    'Amulet es una excelente elección para una invitación moderna.',
    'Fue bonito y, lo más importante, muy cómodo.',
    'Nuestra invitación de boda también se convirtió en un hermoso recuerdo.',
    'Gracias por el trabajo rápido y de calidad.',
    'El diseño era muy limpio, sin nada innecesario.',
    'Todo estaba presentado de forma clara, sencilla y bonita.',
    'Nos encantó el resultado final. Era exactamente nuestro estilo.',
    'La invitación de Amulet le dio un inicio elegante a nuestro evento.',
    'Fue muy cómodo para los invitados, especialmente el mapa y los detalles.',
    'Una solución bonita para cualquier evento.',
    'Nuestra invitación corporativa tenía un aspecto muy profesional.',
    'Fue muy agradable trabajar con ustedes. Todo se organizó rápido y correctamente.',
    'La invitación quedó bonita, moderna y memorable.',
    'Definitivamente recomendaré Amulet a mis amigos.',
    'Una muy buena opción si quieres diferenciarte de las invitaciones comunes.',
    'Todo estaba hecho con mucho gusto y atención.',
    'Nuestros invitados encontraron fácilmente toda la información en un solo lugar.',
    'Muchas gracias por el trabajo bonito y premium.',
    'Gracias a Amulet, nuestra invitación fue no solo informativa, sino también una experiencia emocional y bonita.'
  ],
  de: [
    'Wir haben eine sehr schöne und zarte Einladung erhalten. Alles war geschmackvoll gemacht.',
    'Mit Amulet wurde unsere Hochzeitseinladung besonderer und moderner.',
    'Sehr praktisch: Man sendet den Link und die Gäste sehen sofort alle Informationen.',
    'Das Design wirkte sehr hochwertig und die Nutzung war sehr einfach.',
    'Danke für die schöne Arbeit. Unsere Gäste mochten die Einladung sehr.',
    'Alles wurde schnell, schön und sehr ordentlich vorbereitet.',
    'Wir sind sehr froh, dass wir Amulet gewählt haben. Die Einladung wurde genau so, wie wir sie uns vorgestellt hatten.',
    'Sanfte Farben, schönes Design und eine sehr praktische Lösung.',
    'Unsere Verlobungseinladung war sehr elegant. Vielen Dank.',
    'Eine wunderbare Option für alle, die eine moderne und schöne Einladung möchten.',
    'Jedes Detail war durchdacht. Das Ergebnis war sehr angenehm.',
    'Die Gäste konnten sofort Ort, Uhrzeit und alle Details sehen.',
    'Sehr hochwertige und schöne Arbeit. Ich werde es auf jeden Fall empfehlen.',
    'Amulet gab unserem Event eine besondere Note.',
    'Es war eine sehr schöne, zarte und erinnerungswürdige Einladung.',
    'Sie haben alles schnell vorbereitet und jede Änderung liebevoll umgesetzt.',
    'Das Design war auf sehr hohem Niveau. Wir sind sehr zufrieden.',
    'Unsere Taufeinladung wurde sehr zart und schön.',
    'Es ist sehr praktisch, dass man keine Papiereinladungen braucht.',
    'Wir haben den Link an alle gesendet und alles ließ sich sehr leicht organisieren.',
    'Eine schöne, saubere und moderne Lösung.',
    'Alles war sehr professionell, vom Design bis zum finalen Aussehen.',
    'Vielen Dank für diese schöne Erinnerung.',
    'Die Einladung war geschmackvoll und passte zum Stil unseres Events.',
    'Unsere Geburtstagseinladung wurde sehr fröhlich und schön.',
    'Amulet macht ein Event wirklich besonders.',
    'Es war sehr einfach zu nutzen und sah sehr schön aus.',
    'Viele unserer Gäste fragten, wo wir es bestellt haben.',
    'Wir sind sehr zufrieden mit dem Ergebnis. Alles war schön und klar.',
    'Die Einladung war beeindruckend, besonders auf dem Telefon.',
    'Sehr feine Arbeit. Jedes Detail war an seinem Platz.',
    'Amulet ist eine ausgezeichnete Wahl für moderne Einladungen.',
    'Es war schön und vor allem sehr praktisch.',
    'Unsere Hochzeitseinladung wurde auch zu einer schönen Erinnerung.',
    'Danke für die schnelle und hochwertige Arbeit.',
    'Das Design war sehr sauber, ohne Überflüssiges.',
    'Alles war einfach, verständlich und schön präsentiert.',
    'Wir haben das Endergebnis sehr geliebt. Es war genau unser Stil.',
    'Die Amulet-Einladung gab unserem Event einen eleganten Anfang.',
    'Es war sehr praktisch für die Gäste, besonders der Karten- und Detailbereich.',
    'Eine schöne Lösung für jedes Event.',
    'Unsere Einladung für das Firmenevent sah sehr professionell aus.',
    'Die Zusammenarbeit mit euch war sehr angenehm. Alles wurde schnell und richtig organisiert.',
    'Die Einladung wurde schön, modern und erinnerungswürdig.',
    'Ich werde Amulet definitiv meinen Freunden empfehlen.',
    'Eine sehr gute Option, wenn man sich von normalen Einladungen abheben möchte.',
    'Alles war mit viel Geschmack und Aufmerksamkeit gemacht.',
    'Unsere Gäste fanden alle Informationen sehr leicht an einem Ort.',
    'Vielen Dank für die schöne und hochwertige Arbeit.',
    'Dank Amulet wurde unsere Einladung nicht nur informativ, sondern auch ein emotionales und schönes Erlebnis.'
  ],
  it: [
    'Abbiamo ricevuto un invito molto bello e delicato. Tutto era fatto con gusto.',
    'Con Amulet, il nostro invito di nozze è diventato più unico e moderno.',
    'È molto comodo: invii il link e gli ospiti vedono subito tutte le informazioni.',
    'Il design era molto premium e l’utilizzo molto semplice.',
    'Grazie per il bellissimo lavoro. I nostri ospiti hanno apprezzato molto l’invito.',
    'Tutto è stato preparato velocemente, bene e con grande cura.',
    'Siamo molto felici di aver scelto Amulet. L’invito è venuto esattamente come lo immaginavamo.',
    'Colori delicati, bel design e una soluzione molto comoda.',
    'Il nostro invito di fidanzamento era molto elegante. Grazie.',
    'Un’ottima opzione per chi desidera un invito moderno e bello.',
    'Ogni dettaglio era pensato. Il risultato è stato molto piacevole.',
    'Gli ospiti hanno visto subito luogo, ora e tutti i dettagli.',
    'Lavoro molto bello e di qualità. Lo consiglierò sicuramente.',
    'Amulet ha dato un tocco speciale al nostro evento.',
    'Era un invito molto carino, delicato e memorabile.',
    'Lo hanno preparato rapidamente e hanno fatto ogni modifica con cura.',
    'Il design era di altissimo livello. Siamo molto soddisfatti.',
    'Il nostro invito per il battesimo è venuto molto tenero e bello.',
    'È molto comodo non avere bisogno di inviti cartacei.',
    'Abbiamo inviato il link a tutti e tutto si è organizzato facilmente.',
    'Una soluzione bella, pulita e moderna.',
    'Tutto era molto professionale, dal design all’aspetto finale.',
    'Grazie mille per questo bel ricordo.',
    'L’invito era di buon gusto e adatto allo stile del nostro evento.',
    'Il nostro invito di compleanno è venuto molto allegro e bello.',
    'Amulet rende davvero speciale l’evento.',
    'Era molto facile da usare e l’aspetto era bellissimo.',
    'Molti ospiti ci hanno chiesto dove lo avevamo ordinato.',
    'Siamo molto soddisfatti del risultato. Tutto era bello e chiaro.',
    'L’invito era molto d’effetto, soprattutto aprendolo sul telefono.',
    'Un lavoro molto delicato. Ogni dettaglio era al suo posto.',
    'Amulet è una scelta eccellente per un invito moderno.',
    'Era bello e soprattutto molto comodo.',
    'Il nostro invito di nozze è diventato anche un bel ricordo.',
    'Grazie per il lavoro rapido e di qualità.',
    'Il design era molto pulito, senza elementi inutili.',
    'Tutto era presentato in modo chiaro, semplice e bello.',
    'Abbiamo amato il risultato finale. Era esattamente il nostro stile.',
    'L’invito Amulet ha dato un inizio elegante al nostro evento.',
    'Era molto comodo per gli ospiti, soprattutto la mappa e i dettagli.',
    'Una bella soluzione per qualsiasi evento.',
    'Il nostro invito corporate aveva un aspetto molto professionale.',
    'È stato molto piacevole lavorare con voi. Tutto è stato organizzato velocemente e correttamente.',
    'L’invito è venuto bello, moderno e memorabile.',
    'Consiglierò sicuramente Amulet ai miei amici.',
    'Un’ottima opzione se vuoi distinguerti dagli inviti comuni.',
    'Tutto era fatto con grande gusto e attenzione.',
    'I nostri ospiti hanno trovato facilmente tutte le informazioni in un unico posto.',
    'Grazie per il lavoro bello e premium.',
    'Grazie ad Amulet, il nostro invito è diventato non solo informativo, ma anche un’esperienza emozionante e bella.'
  ],
  ru: [
    'Мы получили очень красивое и нежное приглашение. Всё было сделано со вкусом.',
    'С Amulet наше свадебное приглашение стало более особенным и современным.',
    'Очень удобный вариант: отправляешь ссылку, и гости сразу видят всю информацию.',
    'Дизайн выглядел очень премиально, а пользоваться было очень просто.',
    'Спасибо за красивую работу. Нашим гостям очень понравилось приглашение.',
    'Всё было подготовлено быстро, красиво и очень аккуратно.',
    'Мы очень рады, что выбрали Amulet. Приглашение получилось именно таким, как мы представляли.',
    'Нежные цвета, красивый дизайн и очень удобное решение.',
    'Наше приглашение на помолвку было очень элегантным. Спасибо.',
    'Прекрасный вариант для тех, кто хочет современное и красивое приглашение.',
    'Каждая деталь была продумана. Получился очень приятный результат.',
    'Гости сразу смогли увидеть место, время и все детали.',
    'Очень качественная и красивая работа. Обязательно порекомендую.',
    'Amulet придал нашему событию особое настроение.',
    'Это было очень красивое, нежное и запоминающееся приглашение.',
    'Сделали быстро и с любовью внесли все изменения.',
    'Дизайн был на очень высоком уровне. Мы очень довольны.',
    'Наше приглашение на крещение получилось очень нежным и красивым.',
    'Очень удобно, что не нужны бумажные приглашения.',
    'Мы отправили ссылку всем, и всё организовалось очень легко.',
    'Красивое, чистое и современное решение.',
    'Всё было очень профессионально: от дизайна до финального вида.',
    'Большое спасибо за это красивое воспоминание.',
    'Приглашение было со вкусом и соответствовало стилю нашего события.',
    'Наше приглашение на день рождения получилось очень радостным и красивым.',
    'Amulet действительно делает событие особенным.',
    'Было очень легко пользоваться, а внешний вид был очень красивым.',
    'Многие гости спросили, где мы это заказали.',
    'Мы очень довольны результатом. Всё было красиво и понятно.',
    'Приглашение было впечатляющим, особенно при открытии на телефоне.',
    'Очень нежная работа. Каждая деталь была на своём месте.',
    'Amulet — отличный выбор для современного приглашения.',
    'Было красиво и, главное, очень удобно.',
    'Наше свадебное приглашение стало ещё и красивым воспоминанием.',
    'Спасибо за быструю и качественную работу.',
    'Дизайн был очень чистым, без лишних деталей.',
    'Всё было представлено просто, понятно и красиво.',
    'Нам очень понравился финальный результат. Это был именно наш стиль.',
    'Приглашение Amulet дало нашему событию элегантное начало.',
    'Гостям было очень удобно, особенно раздел с картой и деталями.',
    'Красивое решение для любого события.',
    'Приглашение на наше корпоративное событие выглядело очень профессионально.',
    'Было очень приятно работать с вами. Всё организовали быстро и правильно.',
    'Приглашение получилось красивым, современным и запоминающимся.',
    'Я однозначно порекомендую Amulet друзьям.',
    'Очень хороший вариант, если хотите отличаться от обычных приглашений.',
    'Всё было сделано с большим вкусом и вниманием.',
    'Наши гости легко нашли всю информацию в одном месте.',
    'Большое спасибо за красивую и премиальную работу.',
    'Благодаря Amulet наше приглашение стало не только информативным, но и эмоциональным красивым опытом.'
  ]
};

const hyNames = [
  'Անի Մկրտչյան',
  'Մարիամ Սարգսյան',
  'Լիլիթ Հարությունյան',
  'Նարե Հովհաննիսյան',
  'Սոնա Ավետիսյան',
  'Էլեն Գրիգորյան',
  'Կարեն Պետրոսյան',
  'Արամ Մանուկյան',
  'Գոհար Խաչատրյան',
  'Տաթևիկ Մելքոնյան',
  'Վահե Սիմոնյան',
  'Մանե Մարգարյան',
  'Արփի Կարապետյան',
  'Դավիթ Աբրահամյան',
  'Հասմիկ Նավասարդյան',
  'Նելլի Մկրտումյան',
  'Աննա Մուրադյան',
  'Լուսինե Բաղդասարյան',
  'Արթուր Գևորգյան',
  'Սեդա Հովսեփյան',
  'Նարինե Ղազարյան',
  'Արմեն Սահակյան',
  'Ռուզաննա Խաչիկյան',
  'Մերի Գալստյան',
  'Էդգար Դանիելյան',
  'Սիրանուշ Մինասյան',
  'Հայկ Մարտիրոսյան',
  'Իննա Վարդանյան',
  'Սամվել Խաչատուրով',
  'Քրիստինե Աղաջանյան',
  'Էվա Հարությունյան',
  'Տիգրան Ներսիսյան',
  'Մելինե Ասատրյան',
  'Աշոտ Ավետյան',
  'Սուսաննա Մանվելյան',
  'Ռուբեն Բաբայան',
  'Արմինե Պողոսյան',
  'Միքայել Օհանյան',
  'Աննա Ղուկասյան',
  'Հովհաննես Կարապետյան',
  'Սաթենիկ Մկրտչյան',
  'Էմմա Գրիգորյան',
  'Լևոն Սիմոնյան',
  'Արուսյակ Դավթյան',
  'Նորայր Մելքումյան',
  'Լիանա Աբելյան',
  'Սերգեյ Սարգսյան',
  'Մոնիկա Արամյան',
  'Նաիրա Պետրոսյան',
  'Մհեր Մանուկյան'
];

const latinNames = [
  'Ani Mkrtchyan',
  'Mariam Sargsyan',
  'Lilit Harutyunyan',
  'Nare Hovhannisyan',
  'Sona Avetisyan',
  'Elen Grigoryan',
  'Karen Petrosyan',
  'Aram Manukyan',
  'Gohar Khachatryan',
  'Tatevik Melkonyan',
  'Vahe Simonyan',
  'Mane Margaryan',
  'Arpi Karapetyan',
  'David Abrahamyan',
  'Hasmik Navasardyan',
  'Nelli Mkrtumyan',
  'Anna Muradyan',
  'Lusine Baghdasaryan',
  'Artur Gevorgyan',
  'Seda Hovsepyan',
  'Narine Ghazaryan',
  'Armen Sahakyan',
  'Ruzanna Khachikyan',
  'Meri Galstyan',
  'Edgar Danielyan',
  'Siranush Minasyan',
  'Hayk Martirosyan',
  'Inna Vardanyan',
  'Samvel Khachaturov',
  'Kristine Aghajanyan',
  'Eva Harutyunyan',
  'Tigran Nersisyan',
  'Meline Asatryan',
  'Ashot Avetyan',
  'Susanna Manvelyan',
  'Ruben Babayan',
  'Armine Poghosyan',
  'Mikayel Ohanyan',
  'Anna Ghukasyan',
  'Hovhannes Karapetyan',
  'Satenik Mkrtchyan',
  'Emma Grigoryan',
  'Levon Simonyan',
  'Arusyak Davtyan',
  'Norayr Melkumyan',
  'Liana Abelyan',
  'Sergey Sargsyan',
  'Monika Aramyan',
  'Naira Petrosyan',
  'Mher Manukyan'
];

function makeTestimonials(language) {
  const texts = localizedTexts[language] || localizedTexts.en;
  const names = language === 'hy' ? hyNames : latinNames;
  return texts.map((text, index) => ({
    id: index + 1,
    name: names[index] || names[0],
    text
  }));
}

function ReviewCard({ item }) {
  return (
    <article className="customer-review-card">
      <Quote size={21} aria-hidden="true" />
      <p>{item.text}</p>
      <strong>{item.name}</strong>
    </article>
  );
}

export default function TestimonialV2() {
  const { language, t } = useLanguage();
  const testimonials = makeTestimonials(language);
  const firstRow = testimonials.slice(0, 25);
  const secondRow = testimonials.slice(25);

  return (
    <section className="customer-testimonials-section" aria-labelledby="customer-testimonials-title">
      <div className="customer-testimonials-heading">
        <span><Sparkles size={16} /> {t('customerTestimonialsKicker')}</span>
        <h2 id="customer-testimonials-title">{t('customerTestimonialsTitle')}</h2>
        <p>{t('customerTestimonialsSubtitle')}</p>
      </div>
      <div className="testimonial-v2-marquee" aria-label={t('customerTestimonialsTitle')}>
        <div className="testimonial-v2-row">
          {[...firstRow, ...firstRow].map((item, index) => <ReviewCard key={`top-${language}-${item.id}-${index}`} item={item} />)}
        </div>
        <div className="testimonial-v2-row reverse">
          {[...secondRow, ...secondRow].map((item, index) => <ReviewCard key={`bottom-${language}-${item.id}-${index}`} item={item} />)}
        </div>
      </div>
    </section>
  );
}
